services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: facteur
      POSTGRES_USER: facteur
      POSTGRES_PASSWORD: facteur
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

volumes:
  postgres_data:
